---
apiVersion: v1
kind: Service
metadata:
  name: globus-connect-service
  namespace: globus
  labels:
    k8s-app: globus-connect
spec:
  type: NodePort
  ports: 
  - port: 2811
    targetPort: 2811
    protocol: TCP
  selector:
    k8s-app: globus-connect
