apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: globus-connect-data
  namespace: globus
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
